### ISSUE TITLE
No project file

### ISSUE THREAD

**Issue by gerchicov-bp** [charless3/oauth2-exercise#1]
It seems you submitted all the files except of project file.

If you wanted to submit source files only then why do you submit "appdelegate" and info.plist?

**Comment by charless3** [comment]
Both AppDelegate and info.plist contain useful code for getting OAuth2 to work for Instagram and other non-standard services. If you want to use this code, I suggest starting a new project and initializing it with the NXOAuth2Client cocoapod (v1.2.8). You can then copy the relevant code over pretty easily.

The project file isn't working the way I want (due to a name change after I finished working on it). However, if you can't get the above to work, I suppose I can upload a new version of it.
